export const STORY_ARCHIVE = 'STORY_ARCHIVE';
export const MESSAGES_SET = 'MESSAGES_SET';
export const USERS_SET = 'USERS_SET';
export const USER_SET = 'USER_SET';

export const AUTH_USER_SET = 'AUTH_USER_SET';
export const WARDROBE_USER_SET = 'WARDROBE_USER_SET';

export const SIZE = 'SIZE';
export const STATE_FETCH_SUCCESS = 'STATE_FETCH_SUCCESS';
export const SNIPH_BULK_SUCCESS = 'SNIPH_BULK_SUCCESS';
export const SNIPH_SORT_PARFUMES = 'SNIPH_SORT_PARFUMES';

export const STATE_FETCH = 'STATE_FETCH';
