export var textAesthetic =
  'Clean handlar uteslutande om parfymerna som barafunkar, rakt upp och ner. Mår du allra bäst när du harkontroll och du doftar därefter: okomplicerat, rent,fruktigt och fräscht – oavsett årstid – är den härkollektionen som gjord för dig. Vi varvar här utvaldaparfymer med fokus på solmogen citrus, sydfranskafikon, fräscht päron och finaste mysken.Exempel på dofter vi tidigare valt ut i Clean ärstorsäljaren Solaris EdP från läckra nischparfymhusetAgonist. Den bjuder dig på det mesta och det bästa avsaftiga citrusfrukter. Vi snackar citron, grapefruktoch spännande tagerin som snyggt bryts av medsvartvinbärsblad och svalkande havsvatten. Eller vadsägs om den mer subtila Le Musc & La Peau EdP frånfranska Parfumerie Générale? En intim och självklarkombo av mysk, ren hud och... ja, koll på läget. SniphClean ger dig dofterna som varken komplicerar saker ionödan eller tar mer plats än de behöver.';

export var textAvantGarde =
  'Unisexkollektionen Avant-Garde ger dig experimentella dofter du inte vågat bära. Ännu. Utmana dig själv och din omvärld med ovanliga och lite mer komplexa dofter. Lev utanför din comfort zone, ta chansen att sticka ut och upptäck sidor av dig själv du inte visste du hade. Exempel på dofter vi tidigare valt ut i kollektionen Avant-garde är New York-baserade Gamine Parfums statementdoft Gamine EdP, som kickar loss i ball cannabis, mörk choklad och kaxig patchouli för att sedan landa i en het och oändlig efterfest. I kontrast till den står gröna och gravt beroendeframkallande kokosdoften Coccobello EdP från parisiska Heeley Parfums. Tropiskt, fuktigt och salta havsstänk på ett sätt du aldrig tidigare upplevt det. Och sent ska glömma.';
export var textClean =
  'Clean handlar uteslutande om parfymerna som bara funkar, rakt upp och ner. Mår du allra bäst när du har kontroll och du doftar därefter: okomplicerat, rent, fruktigt och fräscht – oavsett årstid – är den här kollektionen som gjord för dig. Vi varvar här utvalda parfymer med fokus på solmogen citrus, sydfranska fikon, fräscht päron och finaste mysken. Exempel på dofter vi tidigare valt ut i Clean ärstorsäljaren Solaris EdP från läckra nischparfymhusetAgonist. Den bjuder dig på det mesta och det bästa avsaftiga citrusfrukter. Vi snackar citron, grapefruktoch spännande tagerin som snyggt bryts av medsvartvinbärsblad och svalkande havsvatten. Eller vadsägs om den mer subtila Le Musc & La Peau EdP frånfranska Parfumerie Générale? En intim och självklarkombo av mysk, ren hud och... ja, koll på läget. SniphClean ger dig dofterna som varken komplicerar saker ionödan eller tar mer plats än de behöver.';

export var textFemaleClassics =
  'Female Classics ger dig utvalda, tidlösa dofter som bara fortsätter att bevisa sin briljans. Välj denna kollektion om du gillar säkra kort men älskar att få komplimanger och att bli överraskad. Tänk perfekt balans av blommigt, pudrigt och bekant – även om du kommer få dofter du annars inte hade hittat. Exempel på dofter vi tidigare valt ut i kollektionen Female Classics är fina Rose Silence EdP från brittiska parfymmakaren Miller Harris. Bejaka det klassiskt feminina med krispiga rosenblad, sofistikerad patchouli och mjuk mysk. Och en twist av syrlig mandarin. Till den här kollektionen hör även parisiska Histoires de Parfums och den omåttligt populära 1804 EdP. Lyxig ananas och silkeslen persika piffar upp vilken dag som helst i sällskap av mustig nejlika, sensuellt sandelträ och generös vanilj. Gör dig oemotståndlig och svårfångad på samma gång.';

export var textTrendingNow =
  'Trending Now ger dig de senaste trenderna från parfymvärlden. Vare sig det handlar om ett spännande varumärke du bara måste uppleva, en ny parfymlansering eller parfymnoten på doftexperternas läppar. Behöver vi säga mer? Till den här kollektionen har vi tidigare valt ut den efterlängtade lanseringen You or Someone Like You EdP från franska parfymhuset Etat Libre dOrange. Chandler Burr, New York Times tuffa parfymkritiker ger dig sin dofttolkning av Los Angeles-kvinnan i rosor, bubbelbad och lagom berusande blad. Härligt och otippat, på något vis. Lyxigt slipade Vanilla Marble EdP signerad svenska Agonist hör även den till tidigare urvalt i Trending Now.';

export var textWorkPlay =
  'Herrkollektionen Work/Play ger dig noga utvalda dofter för den moderna mannens liv. Från fullspäckad vardag till sena helgnätter. För vem vill göra samma intryck på jobbmötet en måndag som på dejten en fredag? Work/Play är för dig som gillar när allt känns självklart. Och vill dofta därefter. Dofter som tidigare valts ut i Work/Play är exempelvis topprejtade Aqaysos EdP från franska doftgeniet Pierre Guillaumes varumärke, med samma namn. Tänk nyduschat och oemotståndligt fruktigt men med tyngd på det jordiga. Ta nästa plan [Paris – Stockholm Vasastan] och möt underbara Onyx Pearl EdP signerad svenska Agonist. Inbjudande och mystiskt. Intimt och självsäkert. Du kommer vilja ha mer – och du slipper välja.';
